# Generated by Django 3.2.13 on 2022-05-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20220507_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
